#!/usr/bin/php
<?php
    require_once 'header.php';

    if ( $argc < 2 ) {
        die( "Usage: run resource method [args]\n" );
    }
    $_ = array_shift( $argv );
    $resource = array_shift( $argv );
    $method = array_shift( $argv );
    $vars = [];
    foreach ( $argv as $arg ) {
        list( $key, $value ) = explode( '=', $arg, 2 );
        $vars[ $key ] = $value;
    }

    function launchController( $resource, $get, $post = '', $files = '', $httpRequestMethod = 'GET' ) {
        try {
            $controller = controllerBase::findController( $resource );
            $controller->trusted = true;
            $controller->outputFormat = 'text';
            $controller->dispatch( $get, $post, $files, $httpRequestMethod );
        }
        catch ( HTTPErrorException $e ) {
            die( 'An HTTP error occurred: ' . $e->header . ': ' . $e->reason );
        }
        catch ( ErrorRedirectException $e ) {
            launchController( $e->controller, $e->arguments );
        }
    }

    exit( launchController( $resource, [ 'method' => $method ], $vars, [], 'POST' ) );
?>
